DataModeling :
    SupervisedLearning :
        Convex : False
        DecisionTree : False 
        LinearRegression : 
        LogisticRegression : False
        ElasticNet : False
        MultinomialLogisticRegression : False
        NaiveBayesClassification : False
        RandomForest : False
        SupportVectorMachines : False
        GeneralCV : False
    UnsupervisedLearning :
        kMeansClustering : False
        AssociationRules : False
        LDA : False
InferentialStatistics :
    HypothesisTests : False
    Summary: False
Common :
